In [3]:
'''Write Python program to create two matrices (read values from user) and find the following
1. Dot Product
2. Transpose
3. Trace
4. Rank
5. Determinant
6. Inverse
7. Eigen values and eigen vectors'''

import numpy as np
n1 = int(input("Enter the size of the matrix1: "))
print("Enter "+str(n1*n1)+" elements: ")

a1 = [[0] * n1 for i in range(n1)]

for i in range(n1):
    for j in range(n1):
        a1[i][j] = int(input())
        
n2 = int(input("Enter the size of the matrix1: "))
print("Enter "+str(n2*n2)+" elements: ")

a2 = [[0] * n2 for i in range(n2)]

for i in range(n2):
    for j in range(n2):
        a2[i][j] = int(input())

x = np.matrix(a1)
y = np.matrix(a2)

print("Matrix1:\n",x)
print("Matrix2:\n",y)
if(n1 == n2):
    print("Matrix 1 * Matrix 2:\n", np.dot(x,y))
else:
    print("Invalid size")

print("Transpose of matrix1:\n",np.transpose(x))
print("Transpose of matrix2:\n",np.transpose(y))

print("Trace of matrix1:\n",x.trace())
print("Trace of matrix2:\n",y.trace())

print("Rank of matrix1:\n",np.linalg.matrix_rank(x))
print("Rank of matrix2:\n",np.linalg.matrix_rank(y))

print("Determinant of matrix1:\n",np.linalg.det(x))
print("Determinant of matrix2:\n",np.linalg.det(y))

if((np.linalg.det(x)//1)!=0):
    print("Inverse of matrix1:\n",np.linalg.inv(x))
else:
    print("Inverse of matrix1 doesn't exist")

if((np.linalg.det(y)//1)!=0):
    print("Inverse of matrix2:\n",np.linalg.inv(y))
else:
    print("Inverse of matrix2 doesn't exist")


print("Eigenvalues and eigenvectors of matrix1:\n",np.linalg.eig(x))
print("Eigenvalues and eigenvectors of matrix2:\n",np.linalg.eig(y))

Enter the size of the matrix1: 2
Enter 4 elements: 
2
1
2
1
Enter the size of the matrix1: 2
Enter 4 elements: 
1
2
3
4
Matrix1:
 [[2 1]
 [2 1]]
Matrix2:
 [[1 2]
 [3 4]]
Matrix 1 * Matrix 2:
 [[5 8]
 [5 8]]
Transpose of matrix1:
 [[2 2]
 [1 1]]
Transpose of matrix2:
 [[1 3]
 [2 4]]
Trace of matrix1:
 [[3]]
Trace of matrix2:
 [[5]]
Rank of matrix1:
 1
Rank of matrix2:
 2
Determinant of matrix1:
 0.0
Determinant of matrix2:
 -2.0000000000000004
Inverse of matrix1 doesn't exist
Inverse of matrix2:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and eigenvectors of matrix1:
 (array([3., 0.]), matrix([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))
Eigenvalues and eigenvectors of matrix2:
 (array([-0.37228132,  5.37228132]), matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))
