In [11]:
'''Write  a  NumPy  program  to  create  an  element-wise  comparison  (greater,  greater_equal,
less and less_equal) of two given arrays.'''

import numpy as np
x = np.array([1, 2, 5])
y = np.array([3, 4, 5])
print("Array x:", x)
print("Array y:", y)
print("Greater than comparison: ", np.greater(x, y))
print("Greater than or equal to comparison: ", np.greater_equal(x, y))
print("Less than comparison: ", np.less(x, y))
print("Less than or equal to comparison: ", np.less_equal(x, y))

Array x: [1 2 5]
Array y: [3 4 5]
Greater than comparison:  [False False False]
Greater than or equal to comparison:  [False False  True]
Less than comparison:  [ True  True False]
Less than or equal to comparison:  [ True  True  True]


In [6]:
'''Write a NumPyprogram to create an array of all the even integers from 30 to 70.'''
import numpy as np
x = np.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
'''Write a NumPy program to create a 3x3 identity matrix.'''
import numpy as np
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
'''Write  a  NumPy  program  to  create  a  vector  with  values from  0  to  20 and  change  the  sign  of the 
numbers in the range from 9 to 15.'''
import numpy as np
x = np.arange(0,21)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [27]:
'''Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  on  the  
main  diagonal equal to 1, 2, 3, 4, 5.'''
import numpy as np
y = np.diag([1,2,3,4,5])
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [34]:
'''Write  a  NumPy  program  to  compute  sum  of  all  elements,  sum  of  each  
column  and  sum  of each row of a given array.'''
import numpy as np
y = np.array([[1,2,3,4],[1,2,3,5],[6,7,4,3]])
print("Sum of all elements in array: ",np.sum(y))
print("Sum of all elements in a column: ",np.sum(y, axis=0))
print("Sum of all elements in a row: ",np.sum(y, axis=1))

Sum of all elements in array:  41
Sum of all elements in a column:  [ 8 11 10 12]
Sum of all elements in a row:  [10 11 20]


In [43]:
'''Write a NumPy program to save a given array to a text file and load it.'''
import numpy as np
x = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", x)
file = open("file.txt", "w+")
y = str(x)
file.write(y)
file.close()
file = open("file.txt", "r")
y = file.read()
print("file.txt contains:\n", y)
file.close()

Array:
 [[0 2 3]
 [4 5 6]
 [7 8 9]]
file.txt contains:
 [[0 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
'''Write a NumPy program to check whether two arrays are equal (element wise) or not.'''
import numpy as np
x = np.array([1,2,3])
y = np.array([1,2,3])
print(np.equal(x,y))

[ True  True  True]


In [48]:
'''Write  a  NumPy  program  to  create  a  4x4 array  with  random  values,  now  create  a  new  array 
from the said array swapping first and last rows.'''
import numpy as np
x = np.random.rand(4,4)
print(x)
x[[0,3]]=x[[3,0]]
print(x)

[[0.87118948 0.56505359 0.61167081 0.2137929 ]
 [0.40304687 0.55368212 0.67550164 0.07157189]
 [0.55625771 0.78895908 0.24608758 0.89325745]
 [0.1259177  0.98097111 0.98562619 0.80646144]]
[[0.1259177  0.98097111 0.98562619 0.80646144]
 [0.40304687 0.55368212 0.67550164 0.07157189]
 [0.55625771 0.78895908 0.24608758 0.89325745]
 [0.87118948 0.56505359 0.61167081 0.2137929 ]]


In [67]:
'''Write a NumPy program to multiply two given arrays of same size element-by-element.'''
import numpy as np
x = np.array([[1,2,4],[2,3,8]])
y = np.array([[3,4,5],[3,4,5]])
print("Array X:\n",x)
print("Array Y:\n",y)
if(x.shape == y.shape):
    print("Product of elements of X and Y:\n",np.multiply(x,y))
else:
    print("Arrays are of difference sizes")

Array X:
 [[1 2 4]
 [2 3 8]]
Array Y:
 [[3 4 5]
 [3 4 5]]
Product of elements of X and Y:
 [[ 3  8 20]
 [ 6 12 40]]
